[package]
name = "miniupnpc-sys"
version = "0.1.0"
authors = ["Michael Williams <michael.williams@enspiral.com>"]
edition = "2018"
build = "build.rs"

[dependencies]


[build-dependencies]
bindgen = "0.49.0"
pkg-config = "0.3"
cc = "1.0.25"
